name: startup_namer
description: 我的Flutter模板项目

#以下定义应用程序的版本和内部版本号。
#版本号是由点分隔的三个数字，如1.2.43
#后跟一个用“+”分隔的可选内部版本号。
#可以在flutter中覆盖版本号和构建器号
#build通过分别指定--build-name和--build-number。
#在Android中，build-name用作versionName，而build-number用作versionCode。
# 更多关于 Android 版，参考 https://developer.android.com/studio/publish/versioning
# 在iOS中, build-name 用作 CFBundleShortVersionString 而 build-number 用作 CFBundleVersion.
# 更多关于 iOS 版，参考 https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

# environment: 环境
environment:
  sdk: ">=2.1.0 <3.0.0"

# dependencies: 依赖
dependencies:
  flutter:
    sdk: flutter

  # Cupertino 字体、图标库，参考类 CupertinoIcons
  cupertino_icons: ^0.1.2
  # 添加此依赖后点击 Packages get 来安装依赖
  english_words: ^3.1.0

# dev: 开发，开发依赖
dev_dependencies:
  flutter_test:
    sdk: flutter


# 语法参考 https://www.dartlang.org/tools/pub/pubspec

# 针对 flutter 的配置
flutter:

  # 开启材料设计
  uses-material-design: true

# 这样添加 assets: 资产
# assets:
# - images/a_dot_burr.jpeg
# - images/a_dot_ham.jpeg
#
# 若添加图片assert 可以指定分辨率适应，参考 https://flutter.io/assets-and-images/#resolution-aware
#
# 若要从依赖包添加asserts，参考 https://flutter.io/assets-and-images/#from-packages
#
# 这样添加自定义字体
# example:
# fonts:
# - family: Schyler
# fonts:
# - asset: fonts/Schyler-Regular.ttf
# - asset: fonts/Schyler-Italic.ttf
# style: italic
# - family: Trajan Pro
# fonts:
# - asset: fonts/TrajanPro.ttf
# - asset: fonts/TrajanPro_Bold.ttf
# weight: 700
#
# 若要从依赖包添加字体，参考 https://flutter.io/custom-fonts/#from-packages